// <auto-generated />
namespace Online_Shopping.DomainModel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class change5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(change5));
        
        string IMigrationMetadata.Id
        {
            get { return "202012030453149_change5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
